version: '3.8'
services:
  playwright-test:
    image: playwright-test
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run test:mobile
    volumes:
      - ./playwright-report/:/app/playwright-report
      - ./test-resullts/:/app/test-resullts
